spring.application.name=packet-decryptor

# ========================================
# Packet Decryption Configuration
# ========================================

crypto.PrependThumbprint.enable=true

mosip.registration.processor.crypto.decrypt.id=mosip.registration.processor.crypto.decrypt
mosip.registration.processor.application.version=1.0
mosip.registration.processor.datetime.pattern=yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

registration.processor.application.id=REGISTRATION

# Input/Output paths for packet decryption
packet.input.zip.path=D:/packets/abc.zip
packet.output.path=D:/packets/output/
packet.id=10151112800006320260402053435
packet.refId=10151_11280

# Crypto configuration
mosip.kernel.cryptomanager.url=https://api-internal-preprod.nsis.nira.go.ug/v1/keymanager/decrypt

auth.server.admin.issuer.uri=https://iam-preprod.nsis.nira.go.ug/auth/realms/
mosip.iam.adapter.appid=regproc
mosip.iam.adapter.clientid=mosip-regproc-client
mosip.iam.adapter.clientsecret=o2PSckJnNI1fF0mI
mosip.kernel.auth.adapter.ssl-bypass=true
mosip.kernel.auth.appid-realm-map={regproc:'mosip'}
mosip.kernel.auth.appids.realm.map={regproc:'mosip'}
#not needed (available in application-default.properties)
auth.server.admin.allowed.audience=mosip-regproc-client
mosip.authmanager.client-token-endpoint=https://api-internal-preprod.nsis.nira.go.ug/authenticate/clientidsecretkey